FROM python:3.12-slim-bullseye

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

COPY . /app

WORKDIR /app
 
RUN pip install -r requirements.txt

EXPOSE 8080

CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8080"]